#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/doc/claude/settings.hooks.example.json" ]]; then
  PACKAGE_DIR="${SCRIPT_DIR}"
else
  PACKAGE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
fi

PROJECT_DIR="${PWD}"
FORCE=0

usage() {
  cat <<'EOF'
Usage:
  install-claude.sh [--project /path/to/project] [--force]

Installs The One Claude Code runtime into an existing project directory.
Binary and theone.yaml stay in the release package directory; drivers
are installed under <project>/.theone-data/drivers/.

Options:
  --project DIR  Target project opened by Claude Code. Defaults to current directory.
  --force        Overwrite existing runtime files under the target project.
  -h, --help     Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      [[ $# -ge 2 ]] || { echo "[install-claude] --project requires a value" >&2; exit 2; }
      PROJECT_DIR="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[install-claude] unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

PROJECT_DIR="$(cd "${PROJECT_DIR}" && pwd)"
PACKAGE_DIR="$(cd "${PACKAGE_DIR}" && pwd)"

THEONE_BIN="${PACKAGE_DIR}/bin/theone"
HOOKS_TEMPLATE="${PACKAGE_DIR}/doc/claude/settings.hooks.example.json"
MCP_TEMPLATE="${PACKAGE_DIR}/doc/claude/mcp.json"
CONTEXT_TEMPLATE="${PACKAGE_DIR}/doc/claude/context/theone-context.md.template"
CONFIG_TEMPLATE="${PACKAGE_DIR}/theone.yaml"

for required in "${THEONE_BIN}" "${HOOKS_TEMPLATE}" "${MCP_TEMPLATE}" "${CONTEXT_TEMPLATE}" "${CONFIG_TEMPLATE}"; do
  if [[ ! -e "${required}" ]]; then
    echo "[install-claude] missing package file: ${required}" >&2
    exit 1
  fi
done

if [[ ! -x "${THEONE_BIN}" ]]; then
  echo "[install-claude] binary is not executable: ${THEONE_BIN}" >&2
  echo "[install-claude] use the official release package, or rebuild the package before installing" >&2
  exit 1
fi

DATA_DIR="${PROJECT_DIR}/.theone-data"
DRIVERS_DIR="${DATA_DIR}/drivers"
SETTINGS_TARGET="${PROJECT_DIR}/.claude/settings.json"
SETTINGS_FRAGMENT="${PROJECT_DIR}/.claude/settings.theone-hooks.json"
MCP_TARGET="${PROJECT_DIR}/.mcp.json"
SURFACE="${PROJECT_DIR}/.claude/theone-context.md"
INSTALL_ENV="${DATA_DIR}/theone-install.env"

mkdir -p \
  "${PROJECT_DIR}/.claude" \
  "${DATA_DIR}" \
  "${DRIVERS_DIR}/claude_code" \
  "${DRIVERS_DIR}/shared"

copy_tree() {
  local src="$1"
  local dst="$2"
  if [[ -e "${dst}" && "${FORCE}" != "1" ]]; then
    echo "[install-claude] refresh ${dst} without deleting user files"
  fi
  mkdir -p "${dst}"
  cp -R "${src}/." "${dst}/"
}

copy_tree "${PACKAGE_DIR}/drivers/claude_code" "${DRIVERS_DIR}/claude_code"
copy_tree "${PACKAGE_DIR}/drivers/shared" "${DRIVERS_DIR}/shared"

chmod +x "${DRIVERS_DIR}/claude_code/hooks/"*.sh 2>/dev/null || true
chmod +x "${DRIVERS_DIR}/shared/"*.sh 2>/dev/null || true
chmod +x "${DRIVERS_DIR}/shared/"*.py 2>/dev/null || true

cat >"${INSTALL_ENV}" <<EOF
# Generated by install-claude.sh.
THEONE_PACKAGE_DIR="${PACKAGE_DIR}"
THEONE_PROJECT_DIR="${PROJECT_DIR}"
# Optional scope overrides. Defaults prefer Hook payload cwd; THEONE_PROJECT_DIR is fallback only.
# THEONE_PROJECT_ID="$(basename "${PROJECT_DIR}")"
# THEONE_REPO_ID="$(basename "${PROJECT_DIR}")"
EOF

python3 - <<'PY' "${HOOKS_TEMPLATE}" "${SETTINGS_FRAGMENT}" "${PROJECT_DIR}"
import json
import pathlib
import sys

template_path, fragment_path, project_dir = sys.argv[1], sys.argv[2], sys.argv[3]
text = pathlib.Path(template_path).read_text(encoding="utf-8").replace("__THEONE_PROJECT__", project_dir)
pathlib.Path(fragment_path).parent.mkdir(parents=True, exist_ok=True)
pathlib.Path(fragment_path).write_text(text, encoding="utf-8")
json.loads(text)
print(f"[install-claude] wrote fragment: {fragment_path}")
PY

if [[ ! -f "${SETTINGS_TARGET}" ]]; then
  cp "${SETTINGS_FRAGMENT}" "${SETTINGS_TARGET}"
  echo "[install-claude] created ${SETTINGS_TARGET}"
elif command -v jq >/dev/null 2>&1; then
  tmp="$(mktemp)"
  jq -s '.[0] * .[1] | .hooks = ((.[0].hooks // {}) * (.[1].hooks // {}))' \
    "${SETTINGS_TARGET}" "${SETTINGS_FRAGMENT}" >"${tmp}"
  mv "${tmp}" "${SETTINGS_TARGET}"
  echo "[install-claude] merged hooks into ${SETTINGS_TARGET}"
else
  echo "[install-claude] ${SETTINGS_TARGET} exists; install jq or merge ${SETTINGS_FRAGMENT} manually"
fi

MCP_RENDERED="$(python3 - <<'PY' "${MCP_TEMPLATE}" "${PACKAGE_DIR}" "${PROJECT_DIR}"
import json
import pathlib
import sys

template_path, package_dir, project_dir = sys.argv[1], sys.argv[2], sys.argv[3]
text = pathlib.Path(template_path).read_text(encoding="utf-8")
text = text.replace("__THEONE_PACKAGE__", package_dir).replace("__THEONE_PROJECT__", project_dir)
json.loads(text)
print(text, end="")
PY
)"

if [[ ! -f "${MCP_TARGET}" ]]; then
  printf '%s' "${MCP_RENDERED}" >"${MCP_TARGET}"
  echo "[install-claude] created ${MCP_TARGET}"
elif command -v jq >/dev/null 2>&1; then
  tmp="$(mktemp)"
  jq -s '
    (.[0].mcpServers // {}) as $old |
    (.[1].mcpServers // {}) as $new |
    .[0] * .[1] | .mcpServers = ($old * $new)
  ' "${MCP_TARGET}" <(printf '%s' "${MCP_RENDERED}") >"${tmp}"
  mv "${tmp}" "${MCP_TARGET}"
  echo "[install-claude] merged theone into ${MCP_TARGET}"
else
  echo "[install-claude] ${MCP_TARGET} exists; install jq or merge theone MCP block manually"
fi

if [[ ! -f "${SURFACE}" ]]; then
  cp "${CONTEXT_TEMPLATE}" "${SURFACE}"
fi

"${THEONE_BIN}" health -config "${CONFIG_TEMPLATE}" -data-dir "${DATA_DIR}" >/dev/null

echo "[install-claude] installed The One Claude Code runtime"
echo "[install-claude] package: ${PACKAGE_DIR}"
echo "[install-claude] project: ${PROJECT_DIR}"
echo "[install-claude] data:    ${DATA_DIR}"
echo "[install-claude] drivers: ${DRIVERS_DIR}"
echo "[install-claude] next:    restart Claude Code, then check MCP server theone"
